### ISSUE TITLE
<AP> RC500S Mirror Image

### ISSUE THREAD

**Issue by DOD-AP-Sales** [dod-taiwan/Firmware-Issue#5]
5 RC500S customers from AU are asking for mirror image function. Explained that it might be against the law and causing damage about playing cellphone while driving. But they still wanna know the possibility.

**Comment by dod-pm1** [comment]
The possibility is defintely a easy yes; however, please talk to the customer that we strongly do not recommand to open this function, reason being the APP is used by multiple regions including Taiwan, North America, Europe, which these region strongly banned the usage of any eletronics while driving.
In this case, you must operate the smart device before start reversing the vehicle, this is already dangerous and against the law in these regions.

Result, if you cannot use it to reverse the car, flipping the video will only make review harder because everything is mirrorred.

**Comment by DOD-AP-Sales** [comment]
AU agent insists that when reviewing footage in DOD player it is more accurate watching rear footage in mirror image.

**Comment by dod-pm1** [comment]
Please discuss with other regions, if really desired, it is possible to include this, for the last time.
1, we have changed the menus and functions around too many times.
2, changing user manuals and menu tree that often does not make any sense.
3, your client is more of a special case, normally you need to see all the information "up right", not reverse or mirror. Based on laws, if there is any editing of original evidence, it may already considered NOT authentic.

Once again, we do NOT suggest to open this function, if sales agree to, please also consider potential consequences in future.
