### ISSUE TITLE
<AP> RC500S: Option to Reduce Resolution to 720P 

### ISSUE THREAD

**Issue by DOD-AP-Sales** [dod-taiwan/Firmware-Issue#6]
"No option to reduce resolution to 720P or reduce frame rate if you want to get more video files on the SD Card" from AU customer feedback.

**Comment by dod-pm1** [comment]
This is not recommanded.
We had these options before, but then it may produce the concern that our dashcam are not FULLHD, because of these posted videos on youtube or share platform.

**Tech lesson** 
due to our compression method, 720p and 1080p 30/60fps are under 10% difference in file size; therefore, make it 720p or 30fps will NOT significantly increase the amount of saved video.

Close if no further concern, thanks.

**Comment by DOD-AP-Sales** [comment]
ok sure, just ending through customer feedback
